routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Carbon\Carbon;
use App\Models\Bar;
use App\Models\TabletopGame;
use App\Http\Controllers\BarsController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//resources
Route::resource('roles',App\Http\Controllers\RoleController::class);
Route::resource('tabletopgames',App\Http\Controllers\TabletopGameController::class);
Route::resource('slider', App\Http\Controllers\SliderController::class);
Route::resource('/form',App\Http\Controllers\FormController::class);



//public get

Route::get('/', function () {
    return view('auth.login');
});
Route::get('/Register', function() {
    return view('auth.register');
});
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/profile/{id}',[App\Http\Controllers\ProfileController::class, 'user_detail'])->name('user_detail');
Route::get('/Bars/{id}',[App\Http\Controllers\BarController::class, 'bar_detail'])->name('bar_detail');
Route::get('/Games/{id}',[App\Http\Controllers\TabletopGameController::class, 'game_detail'])->name('game_detail');
Route::get('/scan', App\Http\Controllers\ScanController::class . '@scan')->name('scan');
Route::get('/Bars',[App\Http\Controllers\BarController::class, 'Bars'])->name('Bars');
Route::get('/nieuws',[App\Http\Controllers\BarController::class, 'nieuws'])->name('nieuws');
Route::get('/Users',[App\Http\Controllers\ProfileController::class, 'Userlist'])->name('profile');
Route::get('/spellen', [App\Http\Controllers\HomeController::class, 'spellen'])->name('spellen');
Route::get('/gen', App\Http\Controllers\GenerateController::class . '@gen')->name('gen');
Route::get('/Leaderboard',[App\Http\Controllers\LeaderboardController::class, 'Leaderboard'])->name('Leaderboard');

//still need changes


//Route::get('/LeaderBoard', function () {
//    return view('Leaderboard');
//});
Route::get('Games', function () {
    $TabletopGames = TabletopGame::all();
    return view('/Games', compact('TabletopGames'));
});
//end changes

//Auth
Auth::routes();

//Get
Route::get('User', function () {
    return view('userProfile');
});

Route::get('/apicall', function () {
//    lezen van xml file in public
//        $xml = simplexml_load_file('games.xml');
//echo $xml;
    $xmlString = file_get_contents(public_path('games.xml'));

    $xmlObject = simplexml_load_string($xmlString);

    $json = json_encode($xmlObject);

    $games = json_decode($json, true);

    foreach ($games['item'] as $game) {
//    echo "<a href='https://boardgamegeek.com/xmlapi/boardgame/"
//        . $game['@attributes']['objectid']"
//        .</a>"<br>";
        echo "<a href='/apicall/" . $game['@attributes']['objectid'] . "'> " . $game['@attributes']['objectid'] . "</a><br>";

//    <a href='https://boardgamegeek.com/xmlapi/boardgame/
        echo "<img src='" . $game['thumbnail'] . "'><br>";
        echo $game['name'] . "<br>";
    }
});

Route::get('/apicall/{id}', function () {
    $uri = 'https://boardgamegeek.com/xmlapi/boardgame/' . trim($_SERVER['REQUEST_URI'], '/apicall/');
//    die(var_dump($uri));
//    vertaling
    $xmlString = file_get_contents($uri);

    $xmlObject = simplexml_load_string($xmlString);

    $json = json_encode($xmlObject);

    $game = json_decode($json, true);
    echo $game['boardgame']['description'];
});

app/Models/TabletopGame.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
class TabletopGame extends Model
{
    use HasFactory;

    protected $fillable = [
        'title', 'image', 'description'
    ];
//many-to-many
    public function Bar()
    {
        return $this->belongsToMany(Bar::class);
    }

}

app/Http/Controllers/TabletopGameController.php
<?php


namespace App\Http\Controllers;

use App\Models\TabletopGame;
use Illuminate\Http\Request;

class TabletopGameController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tabletopgames = TabletopGame::latest()->paginate(5);

        return view('tabletopgames.index',compact('tabletopgames'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tabletopgames.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'description' => 'required',
        ]);

        $input = $request->all();

        if ($image = $request->file('image')) {
            $destinationPath = 'images/';
            $profileImage = date('YmdHis') . "Downloads" . $image->getClientOriginalExtension();
            $image->move($destinationPath, $profileImage);
            $input['image'] = "$profileImage";
        }

        TabletopGame::create($input);

        return redirect()->route('tabletopgames.index')
            ->with('success','Tabletop game created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\TabletopGame  $tabletopgame
     * @return \Illuminate\Http\Response
     */
    public function show(TabletopGame $tabletopgame)
    {
        return view('tabletopgames.show',compact('tabletopgame'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\TabletopGame  $tabletopgame
     * @return \Illuminate\Http\Response
     */
    public function edit(TabletopGame $tabletopgame)
    {
        return view('tabletopgames.edit',compact('tabletopgame'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\TabletopGame  $tabletopgame
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, TabletopGame $tabletopgame)
    {
        $request->validate([
            'title' => 'required',
            'description' => 'required',
        ]);

        $input = $request->all();

        if ($image = $request->file('image')) {
            $destinationPath = 'images/';
            $profileImage = date('YmdHis') . "Downloads" . $image->getClientOriginalExtension();
            $image->move($destinationPath, $profileImage);
            $input['image'] = "$profileImage";
        }else{
            unset($input['image']);
        }

        $tabletopgame->update($input);

        return redirect()->route('tabletopgames.index')
            ->with('success','TTG updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\TabletopGame  $tabletopgame
     * @return \Illuminate\Http\Response
     */
    public function destroy(TabletopGame $tabletopgame)
    {
        $tabletopgame->delete();

        return redirect()->route('tabletopgames.index')
            ->with('success','Product deleted successfully');
    }


    //Finding data based on Tabletopgame ID and sending all information that belong to said id to .blade file.
    public function game_detail ($id) {
        $TabletopGame = TabletopGame::find($id);
        if (is_null($TabletopGame)){ //return 404 if theres no information found.
            return redirect('/404');
        }
        return view('Game_detail', compact('TabletopGame',));
    }

}

resources/views/tabletopgames/create.blade.php
@extends('tabletopgames.layout')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Add New Product</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('tabletopgames.index') }}"> Back</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('tabletopgames.store') }}" method="POST" enctype="multipart/form-data">
        @csrf

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>title:</strong>
                    <input type="text" name="title" class="form-control" placeholder="title">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Image:</strong>
                    <input type="file" name="image" class="form-control" placeholder="image">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

    </form>
@endsection

resources/views/tabletopgames/edit.blade.php
@extends('tabletopgames.layout')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Tabletop Game</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('tabletopgames.index') }}"> Back</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('tabletopgames.update',$tabletopgame->id) }}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Title:</strong>
                    <input type="text" name="title" value="{{ $tabletopgame->title }}" class="form-control" placeholder="Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Image:</strong>
                    <input type="file" name="image" class="form-control" placeholder="image">
                    <img src="/images/{{ $tabletopgame->image }}" width="300px">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

    </form>
@endsection

resources/views/tabletopgames/index.blade.php
@extends('tabletopgames.layout')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Laravel 9 CRUD with Image </h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('tabletopgames.create') }}"> Create New TTG</a>
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Image</th>
            <th>Name</th>
            <th>Details</th>
            <th width="280px">Action</th>
        </tr>
        @foreach ($tabletopgames as $tabletopgame)
            <tr>
                <td>{{ ++$i }}</td>
                <td><img src="/images/{{ $tabletopgame->image }}" width="100px"></td>
                <td>{{ $tabletopgame->title }}</td>
                <td>
                    <form action="{{ route('tabletopgames.destroy',$tabletopgame->id) }}" method="POST">

                        <a class="btn btn-info" href="{{ route('tabletopgames.show',$tabletopgame->id) }}">Show</a>

                        <a class="btn btn-primary" href="{{ route('tabletopgames.edit',$tabletopgame->id) }}">Edit</a>

                        @csrf
                        @method('DELETE')

                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </td>
                <td>{{ $tabletopgame->updated_at
                             ->format('d/m/Y') }}</td>
            </tr>
        @endforeach
    </table>

    {!! $tabletopgames->links() !!}

@endsection

resources/views/tabletopgames/layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Laravel 9 CRUD with Image Upload Application - ItSolutionStuff.com</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

<div class="container">
    @yield('content')
</div>

</body>
</html>

resources/views/tabletopgames/show.blade.php
@extends('tabletopgames.layout')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show Tabletop Game</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('tabletopgames.index') }}"> Back</a>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Title:</strong>
                {{ $tabletopgame->title }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Image:</strong>
                <img src="/images/{{ $tabletopgame->image }}" width="500px">
            </div>
        </div>
    </div>
@endsection