routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Carbon\Carbon;
use App\Models\Bar;
use App\Models\TabletopGame;
use App\Http\Controllers\BarsController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//resources
Route::resource('roles',App\Http\Controllers\RoleController::class);
Route::resource('tabletopgames',App\Http\Controllers\TabletopGameController::class);
Route::resource('slider', App\Http\Controllers\SliderController::class);
Route::resource('/form',App\Http\Controllers\FormController::class);



//public get

Route::get('/', function () {
    return view('auth.login');
});
Route::get('/Register', function() {
    return view('auth.register');
});
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/profile/{id}',[App\Http\Controllers\ProfileController::class, 'user_detail'])->name('user_detail');
Route::get('/Bars/{id}',[App\Http\Controllers\BarController::class, 'bar_detail'])->name('bar_detail');
Route::get('/Games/{id}',[App\Http\Controllers\TabletopGameController::class, 'game_detail'])->name('game_detail');
Route::get('/scan', App\Http\Controllers\ScanController::class . '@scan')->name('scan');
Route::get('/Bars',[App\Http\Controllers\BarController::class, 'Bars'])->name('Bars');
Route::get('/nieuws',[App\Http\Controllers\BarController::class, 'nieuws'])->name('nieuws');
Route::get('/Users',[App\Http\Controllers\ProfileController::class, 'Userlist'])->name('profile');
Route::get('/spellen', [App\Http\Controllers\HomeController::class, 'spellen'])->name('spellen');
Route::get('/gen', App\Http\Controllers\GenerateController::class . '@gen')->name('gen');
Route::get('/Leaderboard',[App\Http\Controllers\LeaderboardController::class, 'Leaderboard'])->name('Leaderboard');

//still need changes


//Route::get('/LeaderBoard', function () {
//    return view('Leaderboard');
//});
Route::get('Games', function () {
    $TabletopGames = TabletopGame::all();
    return view('/Games', compact('TabletopGames'));
});
//end changes

//Auth
Auth::routes();

//Get
Route::get('User', function () {
    return view('userProfile');
});

Route::get('/apicall', function () {
//    lezen van xml file in public
//        $xml = simplexml_load_file('games.xml');
//echo $xml;
    $xmlString = file_get_contents(public_path('games.xml'));

    $xmlObject = simplexml_load_string($xmlString);

    $json = json_encode($xmlObject);

    $games = json_decode($json, true);

    foreach ($games['item'] as $game) {
//    echo "<a href='https://boardgamegeek.com/xmlapi/boardgame/"
//        . $game['@attributes']['objectid']"
//        .</a>"<br>";
        echo "<a href='/apicall/" . $game['@attributes']['objectid'] . "'> " . $game['@attributes']['objectid'] . "</a><br>";

//    <a href='https://boardgamegeek.com/xmlapi/boardgame/
        echo "<img src='" . $game['thumbnail'] . "'><br>";
        echo $game['name'] . "<br>";
    }
});

Route::get('/apicall/{id}', function () {
    $uri = 'https://boardgamegeek.com/xmlapi/boardgame/' . trim($_SERVER['REQUEST_URI'], '/apicall/');
//    die(var_dump($uri));
//    vertaling
    $xmlString = file_get_contents($uri);

    $xmlObject = simplexml_load_string($xmlString);

    $json = json_encode($xmlObject);

    $game = json_decode($json, true);
    echo $game['boardgame']['description'];
});

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    use HasFactory;


    public function user()
    {
        return $this->belongsToMany(User::class);
    }

}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Role;
use App\Http\Requests\StoreRoleRequest;
use App\Http\Requests\UpdateRoleRequest;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $roles = Role::orderBy('updated_at', 'desc')->get();

        return view('roles.index', compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('roles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreRoleRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRoleRequest $request)
    {
//        return $request;
        $role = new Role();
        $role->title = $request->title;
        $role->save();
        return redirect('roles');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function show(Role $role)
    {
        return view('roles.show', compact('role'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {
        return view('roles.edit', compact('role'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateRoleRequest  $request
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRoleRequest $request, Role $role)
    {
        //return request();
        $role = Role::find($role->id);
        $role->title = $request->title;
        $role->save();
        return redirect('roles');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        $role->delete();

//        $roleToDelete = Role::find($role->id);
//        $roleToDelete->delete();
        return redirect('roles');
    }
}

resources/views/roles/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"><h1>roles</h1></div>

                <div class="card-body">
                    <form action="{{ route('roles.store') }}"
                        method="post">
                        @csrf
                    <label for="title">rolnaam</label>
                    <input type="text" name="title" id="title">
                    <button type="submit">voeg toe</button>

                    </form>
                </div>

            </div>

        </div>

    </div>
{{--    <strong>{{$role->title}}</strong>  <br>--}}
{{--    @foreach($role->userRole as $user)--}}
{{--        &nbsp;{{$user->name}} <br>--}}
{{--    @endforeach--}}

</div>
@endsection

resources/views/roles/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"><h1>roles</h1></div>

                <div class="card-body">
                    <form  action="{{ route('roles.update', $role->id) }}"
                        method="post">
                        @csrf
                        @method('patch')
                    <label for="title">rolnaam</label>
                    <input type="text" name="title" id="title" value="{{ $role->title }}">
                    <button class="btn btn-outline-primary btn-sm" type="submit">update</button>

                    </form>
                </div>

            </div>

        </div>

    </div>
{{--    <strong>{{$role->title}}</strong>  <br>--}}
{{--    @foreach($role->userRole as $user)--}}
{{--        &nbsp;{{$user->name}} <br>--}}
{{--    @endforeach--}}

</div>
@endsection

resources/views/roles/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <h1>roles</h1>
                <a class="btn btn-outline-info btn-sm" href="{{ route('roles.create') }}">make role</a>
                </div>
                    <div class="card-body">
                    <ul class="list-group">
                        @foreach($roles as $role)
                            <li class="list-group-item" style="list-style: none;">


                                <form style="display: inline-block; float: right" action="{{ route('roles.destroy', $role->id) }}" method="post">
                                    @csrf
                                    @method('delete')
                                    <button class="btn btn-outline-danger btn-sm float-end m-1" type="submit"><i class="fa-solid fa-trash-can"></i></button>
                                </form>
                                <a href="{{ route('roles.show', $role->id) }}">{{ $role->title }}</a>
                                <a class="btn btn-outline-info btn-sm float-end m-1" href="{{ route('roles.edit', $role->id) }}"><i class="fa-solid fa-wrench"></i></a>
                            </li>
                        @endforeach
                    </ul>
                </div>

            </div>

        </div>

    </div>
{{--    <strong>{{$role->title}}</strong>  <br>--}}
{{--    @foreach($role->userRole as $user)--}}
{{--        &nbsp;{{$user->name}} <br>--}}
{{--    @endforeach--}}

</div>
@endsection

resources/views/roles/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"><h1>{{$role->title}}</h1></div>

                <div class="card-body">
                    <ul>
                        @foreach($role->userRole as $user)
                            <li>{{ $user->name }}</li>
                        @endforeach
                    </ul>
                </div>

            </div>

        </div>

    </div>
{{--    <strong>{{$role->title}}</strong>  <br>--}}
{{--    @foreach($role->userRole as $user)--}}
{{--        &nbsp;{{$user->name}} <br>--}}
{{--    @endforeach--}}

</div>
@endsection